import cloro from './assets/products/cloro.png'
import amaciante from './assets/products/amaciante.png'
import detergente from './assets/products/detergente.png'
import desinfetante from './assets/products/desinfetante.png'
import sabao from './assets/products/sabao.png'

export const WHATSAPP_NUMBER = '5521986253642'
export const WHATSAPP_DISPLAY = '(21) 98625-3642'

export const products = [
  { id: 'cloro', name: 'Cloro', qty: '2 Litros', price: 8.99, img: cloro },
  { id: 'amaciante', name: 'Amaciante', qty: '2 Litros', price: 9.99, img: amaciante },
  { id: 'detergente', name: 'Detergente', qty: '2 Litros', price: 8.99, img: detergente },
  { id: 'desinfetante', name: 'Desinfetante', qty: '2 Litros', price: 8.99, img: desinfetante },
  { id: 'sabao', name: 'Sabão Líquido', qty: '2 Litros', price: 9.99, img: sabao },
]

export const kitBottles = [cloro, amaciante, detergente, desinfetante, sabao]

export const kits = [
  { id: 'kit-1l', label: '1 LITRO', price: '23,99', priceValue: 23.99 },
  { id: 'kit-2l', label: '2 LITROS', price: '39,90', priceValue: 39.9 },
  { id: 'kit-3l', label: '3 LITROS', price: '59,99', priceValue: 59.99 },
  { id: 'kit-5l', label: '5 LITROS', price: '119,90', priceValue: 119.9 },
]

export const paymentMethods = ['Pix', 'Dinheiro', 'Cartão de Crédito', 'Cartão de Débito']

export const galleryCategories = [
  { id: 'todos', label: 'Todos' },
  { id: 'caixa-dagua', label: "Caixa d'Água" },
  { id: 'dedetizacao', label: 'Dedetização' },
  { id: 'limpeza-terreno', label: 'Limpeza de Terreno' },
  { id: 'esquadrias', label: 'Portas e Janelas' },
]

export const galleryItems = [
  {
    id: 'gt-antes-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno-antes-1',
  },
  {
    id: 'gt-antes-2',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno-antes-2',
  },
  {
    id: 'gt-antes-3',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno-antes-3',
  },
  {
    id: 'gt-depois-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-1',
  },
  {
    id: 'gt-depois-2',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-2',
  },
  {
    id: 'gt-depois-3',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-3',
  },
  {
    id: 'gt-depois-4',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-4',
  },
  {
    id: 'gt-depois-5',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-5',
  },
  {
    id: 'gt-depois-6',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-6',
  },
  {
    id: 'gt-depois-7',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-7',
  },
  {
    id: 'gt-depois-8',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-8',
  },
  {
    id: 'gt-depois-9',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-9',
  },
  {
    id: 'gt-depois-10',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-10',
  },
  {
    id: 'gt-depois-11',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-11',
  },
  {
    id: 'gt-depois-12',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno-depois-12',
  },
  {
    id: 'gt2-antes-1',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-1',
  },
  {
    id: 'gt2-antes-2',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-2',
  },
  {
    id: 'gt2-antes-3',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-3',
  },
  {
    id: 'gt2-antes-4',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-4',
  },
  {
    id: 'gt2-antes-5',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-5',
  },
  {
    id: 'gt2-antes-6',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-6',
  },
  {
    id: 'gt2-depois-1',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Depois",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-depois-1',
  },
  {
    id: 'gt2-depois-2',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Depois",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-depois-2',
  },
  {
    id: 'gt2-depois-3',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Depois",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-depois-3',
  },
  {
    id: 'gt2-depois-4',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Depois",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-depois-4',
  },
  {
    id: 'gt3-antes-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-antes-1',
  },
  {
    id: 'gt3-antes-2',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-antes-2',
  },
  {
    id: 'gt3-antes-3',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-antes-3',
  },
  {
    id: 'gt3-depois-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-depois-1',
  },
  {
    id: 'gt3-depois-2',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-depois-2',
  },
  {
    id: 'gt3-depois-3',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno2-depois-3',
  },
  {
    id: 'ge-1',
    category: 'esquadrias',
    title: 'Instalação de Porta e Janela de Alumínio',
    location: 'São Gonçalo - RJ',
    img: 'esquadria-1',
  },
  {
    id: 'ge-2',
    category: 'esquadrias',
    title: 'Instalação de Janela de Alumínio',
    location: 'São Gonçalo - RJ',
    img: 'esquadria-2',
  },
  {
    id: 'ge-3',
    category: 'esquadrias',
    title: 'Instalação de Janela de Alumínio',
    location: 'São Gonçalo - RJ',
    img: 'esquadria-3',
  },
  {
    id: 'ge-4',
    category: 'esquadrias',
    title: 'Instalação de Janela de Alumínio',
    location: 'São Gonçalo - RJ',
    img: 'esquadria-4',
  },
  {
    id: 'ge-5',
    category: 'esquadrias',
    title: 'Instalação de Janelas de Alumínio',
    location: 'São Gonçalo - RJ',
    img: 'esquadria-5',
  },
  {
    id: 'gt4-antes-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno Comercial - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno3-antes-1',
  },
  {
    id: 'gt4-antes-2',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno Comercial - Antes',
    location: 'São Gonçalo - RJ',
    img: 'terreno3-antes-2',
  },
  {
    id: 'gt4-depois-1',
    category: 'limpeza-terreno',
    title: 'Limpeza de Terreno Comercial - Depois',
    location: 'São Gonçalo - RJ',
    img: 'terreno3-depois-1',
  },
  {
    id: 'gc-antes-1',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Antes',
    location: 'São Gonçalo - RJ',
    img: 'calcada-antes-1',
  },
  {
    id: 'gc-antes-2',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Antes',
    location: 'São Gonçalo - RJ',
    img: 'calcada-antes-2',
  },
  {
    id: 'gc-depois-1',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Depois',
    location: 'São Gonçalo - RJ',
    img: 'calcada-depois-1',
  },
  {
    id: 'gc-depois-2',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Depois',
    location: 'São Gonçalo - RJ',
    img: 'calcada-depois-2',
  },
  {
    id: 'gc-depois-3',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Depois',
    location: 'São Gonçalo - RJ',
    img: 'calcada-depois-3',
  },
  {
    id: 'gc-depois-4',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro - Depois',
    location: 'São Gonçalo - RJ',
    img: 'calcada-depois-4',
  },
  {
    id: 'gt2-antes-7',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-7',
  },
  {
    id: 'gt2-antes-8',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real-antes-8',
  },
  {
    id: 'gd-1',
    category: 'dedetizacao',
    title: 'Dedetização Residencial',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-1',
  },
  {
    id: 'gd-2',
    category: 'dedetizacao',
    title: 'Dedetização Residencial',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-2',
  },
  {
    id: 'gd-3',
    category: 'dedetizacao',
    title: 'Dedetização de Jardim',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-3',
  },
  {
    id: 'gd-4',
    category: 'dedetizacao',
    title: 'Dedetização de Jardim',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-4',
  },
  {
    id: 'gd-5',
    category: 'dedetizacao',
    title: 'Dedetização de Área Externa',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-5',
  },
  {
    id: 'gd-6',
    category: 'dedetizacao',
    title: 'Dedetização Interna',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-6',
  },
  {
    id: 'gd-7',
    category: 'dedetizacao',
    title: 'Dedetização Interna',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-7',
  },
  {
    id: 'gd-8',
    category: 'dedetizacao',
    title: 'Dedetização Interna',
    location: 'São Gonçalo - RJ',
    img: 'dedetizacao-real-8',
  },
  {
    id: 'gt4-1',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-1',
  },
  {
    id: 'gt4-2',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-2',
  },
  {
    id: 'gt4-3',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-3',
  },
  {
    id: 'gt4-4',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-4',
  },
  {
    id: 'gt4-5',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-5',
  },
  {
    id: 'gt4-6',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-6',
  },
  {
    id: 'gt4-7',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-7',
  },
  {
    id: 'gt4-8',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-8',
  },
  {
    id: 'gt4-9',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-9',
  },
  {
    id: 'gt4-10',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-10',
  },
  {
    id: 'gt4-11',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-11',
  },
  {
    id: 'gt4-12',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-12',
  },
  {
    id: 'gt4-13',
    category: 'limpeza-terreno',
    title: 'Roçagem e Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    img: 'terreno4-foto-13',
  },
  {
    id: 'gt2-antes-9',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real2-antes-1',
  },
  {
    id: 'gt2-antes-10',
    category: 'caixa-dagua',
    title: "Lavagem de Caixa d'Água - Antes",
    location: 'São Gonçalo - RJ',
    img: 'caixa-real2-antes-2',
  },
  {
    id: 'gc2-1',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro',
    location: 'São Gonçalo - RJ',
    img: 'calcada2-foto-1',
  },
  {
    id: 'gc2-2',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro',
    location: 'São Gonçalo - RJ',
    img: 'calcada2-foto-2',
  },
  {
    id: 'gc2-3',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro',
    location: 'São Gonçalo - RJ',
    img: 'calcada2-foto-3',
  },
  {
    id: 'gc2-4',
    category: 'limpeza-terreno',
    title: 'Roçagem de Calçada e Muro',
    location: 'São Gonçalo - RJ',
    img: 'calcada2-foto-4',
  },
]

export const beforeAfterItems = [
  {
    id: 'ba-terreno',
    title: 'Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    before: 'terreno-antes-1',
    after: 'terreno-depois-1',
  },
  {
    id: 'ba-caixa',
    title: "Lavagem de Caixa d'Água",
    location: 'São Gonçalo - RJ',
    before: 'caixa-real-antes-1',
    after: 'caixa-real-depois-1',
  },
  {
    id: 'ba-terreno2',
    title: 'Limpeza de Terreno',
    location: 'São Gonçalo - RJ',
    before: 'terreno2-antes-1',
    after: 'terreno2-depois-1',
  },
  {
    id: 'ba-terreno3',
    title: 'Limpeza de Terreno Comercial',
    location: 'São Gonçalo - RJ',
    before: 'terreno3-antes-1',
    after: 'terreno3-depois-1',
  },
  {
    id: 'ba-calcada',
    title: 'Roçagem de Calçada e Muro',
    location: 'São Gonçalo - RJ',
    before: 'calcada-antes-1',
    after: 'calcada-depois-1',
  },
]

export const services = [
  { id: 'caixa-dagua', icon: 'bucket', name: "Lavagem de Caixa d'Água" },
  { id: 'dedetizacao', icon: 'bug', name: 'Dedetização e Desinsetização' },
  { id: 'pos-obra', icon: 'mop', name: 'Limpeza Pós Obra' },
  { id: 'comercial', icon: 'buildings', name: 'Limpeza Comercial' },
  { id: 'higienizacao', icon: 'spray', name: 'Higienização e Sanitização' },
  { id: 'desentupimento', icon: 'pipe', name: 'Desentupimento em Geral' },
  { id: 'venda', icon: 'bottle', name: 'Venda de Produtos' },
]

export const whyItems = [
  { icon: 'shield', name: 'Produtos de Alta Qualidade' },
  { icon: 'handdollar', name: 'Preços Justos e Competitivos' },
  { icon: 'truck', name: 'Entrega Rápida e Segura' },
  { icon: 'headset', name: 'Atendimento Rápido e Humano' },
  { icon: 'handshake', name: 'Confiança e Credibilidade' },
  { icon: 'smiley', name: 'Satisfação Garantida' },
]

export const testimonials = [
  {
    name: 'Maria Silva',
    initials: 'MS',
    text: 'Produtos excelentes e entrega super rápida! Atendimento nota 10!',
  },
  {
    name: 'Carlos Souza',
    initials: 'CS',
    text: 'Melhor custo-benefício que já encontrei. Recomendo muito!',
  },
  {
    name: 'Juliana Martins',
    initials: 'JM',
    text: 'Tudo sempre muito bem embalado e entregue no prazo.',
  },
]

export const footerLinks = [
  { label: 'Início', href: '#inicio' },
  { label: 'Produtos', href: '#produtos' },
  { label: 'Kits', href: '#kits' },
  { label: 'Serviços', href: '#servicos' },
  { label: 'Galeria', href: '#galeria' },
  { label: 'Indique e Ganhe', href: '#indique' },
  { label: 'Sobre', href: '#sobre' },
  { label: 'Contato', href: '#contato' },
]
